trigger:
  paths:
    include:
      - src/LiteNetwork.Server/*
      - src/LiteNetwork.Common/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

- script: |
    dotnet build src/LiteNetwork.Server/LiteNetwork.Server.csproj --configuration Release
  displayName: 'Build'

- script: |
    dotnet test tests/LiteNetwork.Server.Tests/LiteNetwork.Server.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*"
  displayName: 'Test'

- script: |
    bash <(curl -s https://codecov.io/bash)
  displayName: 'Uploading coverage'